### ISSUE TITLE
Change description to refer to as "Unofficial client"

### ISSUE THREAD

**Issue by brhx** [ArkinSolomon/spanish-dict-client#1]
Thank you for this package! :)

You've described it as being "not an actual API, it is sort of like one". You my friend have made a piece of client software for [spanishdict.com](https://spanishdict.com), and as it's not officially affiliated with them, it's an "unofficial client".

**Comment by ArkinSolomon** [comment]
I will change that as soon as I can. Thanks for the suggestion!

**Comment by ArkinSolomon** [comment]
#d574d9a

**Comment by ArkinSolomon** [comment]
#d574d9a23f807535e134119144dc616743a6fe90

**Comment by ArkinSolomon** [comment]
Commit d574d9a23f807535e134119144dc616743a6fe90 closes #1
